steps:

# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cache
- name: 'gcr.io/$PROJECT_ID/restore_cache'
  waitFor: ['-']
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=cargo-home-release-$( checksum Cargo.lock )'
  id: 'cargo-home'

# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cache
- name: 'gcr.io/$PROJECT_ID/restore_cache'
  waitFor: ['-']
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=cargo-target-release-$( checksum Cargo.lock )'
  id: 'cargo-target'

- name: 'gcr.io/$PROJECT_ID/restore_cache'
  waitFor: ['-']
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=sccache'
  id: 'sccache'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/rust_base || true
    docker build -f Dockerfile.base --cache-from gcr.io/$PROJECT_ID/rust_base \
      -t gcr.io/$PROJECT_ID/rust_base:$COMMIT_SHA \
      -t gcr.io/$PROJECT_ID/rust_base .
  waitFor: ['-']
  id: 'build_rust_base'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/simulator || true
    cd ./simulator
    docker build --cache-from gcr.io/$PROJECT_ID/simulator \
      -t gcr.io/$PROJECT_ID/simulator:$COMMIT_SHA \
      -t gcr.io/$PROJECT_ID/simulator .
  waitFor: ['-']

- name: 'gcr.io/$PROJECT_ID/rust_base'
  args: ['cargo', 'fmt', '--', '--check']
  waitFor: ['build_rust_base']

# from https://hub.docker.com/_/rust
- name: 'gcr.io/$PROJECT_ID/rust_base'
  args: ['cargo', 'build', '--release']
  waitFor: ['cargo-home', 'cargo-target', 'build_rust_base', 'sccache']
  id: 'cargo-build'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find target/ -maxdepth 2 -executable -type f | sed -e s/^/\!/ >> .dockerignore

    docker build -t gcr.io/$PROJECT_ID/solver \
    -t gcr.io/$PROJECT_ID/solver:$COMMIT_SHA \
    --build-arg SOLVER_REVISION=$COMMIT_SHA \
    .
  waitFor: ['cargo-build']

# from https://hub.docker.com/_/rust
- name: 'gcr.io/$PROJECT_ID/rust_base'
  args: ['cargo', 'test', '--release']
  waitFor: ['cargo-build']
  id: 'cargo-test'

# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cache
- name: 'gcr.io/$PROJECT_ID/save_cache'
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=cargo-home-release-$( checksum Cargo.lock )'
  # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
  - '--path=cargo_home/bin'
  - '--path=cargo_home/registry/index'
  - '--path=cargo_home/registry/cache'
  - '--path=cargo_home/git/db'
  - '--no-clobber'
  waitFor: ['cargo-test']

# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cache
- name: 'gcr.io/$PROJECT_ID/save_cache'
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=cargo-target-release-$( checksum Cargo.lock )'
  # https://doc.rust-lang.org/cargo/guide/build-cache.html
  - '--path=target/release'
  waitFor: ['cargo-test']

# https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/cache
- name: 'gcr.io/$PROJECT_ID/save_cache'
  args:
  - '--bucket=gs://$_CACHE_BUCKET'
  - '--key=sccache'
  - '--path=sccache'
  waitFor: ['cargo-test']

timeout: 1200s

images:
- 'gcr.io/$PROJECT_ID/solver'
- 'gcr.io/$PROJECT_ID/solver:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/rust_base'
- 'gcr.io/$PROJECT_ID/rust_base:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/simulator'
- 'gcr.io/$PROJECT_ID/simulator:$COMMIT_SHA'

options:
  env:
    - 'CARGO_HOME=/workspace/cargo_home'
    # https://github.com/mozilla/sccache#local
    - 'SCCACHE_DIR=/workspace/sccache'


substitutions:
  _CACHE_BUCKET: negainoido-icfpc-2020_cloudbuild
